version: '3'

services:
  server:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - app
  app:
    container_name: php
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
  db:
    container_name: animalsDB
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LKJasd789
      MYSQL_DATABASE: animalsDb
      MYSQL_USER: noredis
      MYSQL_PASS: Qwerty123
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: